version: "3.7"

services:
  
  sennet-auth:
    # Use the published image and tag from DockerHub
    image: sennet/sennet-auth:${HUBMAP_AUTH_VERSION:?err}
    environment:
      - DEPLOY_MODE=prod
    ports:
      # Proxy pass to workspaces REST API on PSC VM
      - "7777:7777"
      # spatial-api
      - "8888:8888"
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "./sennet-auth/src/instance:/usr/src/app/src/instance"
      # Mount conf.d-prod to the nginx conf.d on container
      - "./nginx/conf.d-prod:/etc/nginx/conf.d"
      # Mount ssl certificates from host to container
      - "/etc/letsencrypt:/etc/letsencrypt"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.prod.json:/usr/src/app/api_endpoints.json"
