version: "3.7"

services:
  
  sennet-auth:
    # Use the published image and tag from DockerHub
    image: sennet/sennet-auth:${SENNET_AUTH_VERSION:?err}
    environment:
      - DEPLOY_MODE=prod
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "./sennet-auth/src/instance:/usr/src/app/src/instance"
      # Mount conf.d-prod to the nginx conf.d on container
      - "./nginx/conf.d-prod:/etc/nginx/conf.d"
      # Mount ssl certificates from host to container
      - "/etc/letsencrypt:/etc/letsencrypt"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.prod.json:/usr/src/app/api_endpoints.json"
